In [35]:
import pandas as pd

In [36]:
df=pd.read_csv('Amazondata.csv')

In [37]:
df

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,31-01-2023,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,30-12-2023,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,10-05-2022,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,18-07-2023,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,04-02-2023,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD0099996,07-03-2023,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,NaN,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,24-11-2021,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,NaN,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,29-04-2023,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,NaN,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,01-11-2021,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,NaN,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,04-12-2021,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

In [38]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,31-01-2023,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,30-12-2023,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,10-05-2022,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,18-07-2023,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,04-02-2023,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [39]:
df.tail()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
99995,ORD0099996,07-03-2023,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,NaN,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,24-11-2021,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,NaN,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,29-04-2023,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,NaN,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,01-11-2021,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,NaN,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,04-12-2021,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  object
 1   OrderDate      100000 non-null  object
 2   CustomerID     100000 non-null  object
 3   CustomerName   100000 non-null  object
 4   ProductID      100000 non-null  object
 5   ProductName    100000 non-null  object
 6   Category       100000 non-null  object
 7   Brand          100000 non-null  object
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       99918 non-null   float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  object
 15  OrderStatus    100000 non-null  object
 16  City           100000 non-null  object
 17  State          100000 non-null  object
 18  Country        100000 non-null  object
 19  SellerID       100000 non-null  object
dtypes: float64(5), int64(1), object(14)
memory usage: 15.3+ MB

In [41]:
df.describe()

,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount
count,100000.000000,100000.000000,99918.000000,100000.000000,100000.000000,100000.000000
mean,3.001400,302.905748,0.074287,68.468902,7.406660,918.256479
std,1.413548,171.840797,0.082590,74.131180,4.324057,724.508332
min,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000
25%,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000
50%,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000
75%,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000
max,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000

In [42]:
df.isnull().sum()

OrderID           0
OrderDate         0
CustomerID        0
CustomerName      0
ProductID         0
ProductName       0
Category          0
Brand             0
Quantity          0
UnitPrice         0
Discount         82
Tax               0
ShippingCost      0
TotalAmount       0
PaymentMethod     0
OrderStatus       0
City              0
State             0
Country           0
SellerID          0
dtype: int64

In [43]:
df.fillna(0,inplace=True)

In [44]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount',
       'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='object')

In [47]:
df.shape

(100000, 20)

In [48]:
df.dtypes

OrderID           object
OrderDate         object
CustomerID        object
CustomerName      object
ProductID         object
ProductName       object
Category          object
Brand             object
Quantity           int64
UnitPrice        float64
Discount         float64
Tax              float64
ShippingCost     float64
TotalAmount      float64
PaymentMethod     object
OrderStatus       object
City              object
State             object
Country           object
SellerID          object
dtype: object

In [49]:
df.sort_values('TotalAmount',ascending=False)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
48442,ORD0048443,12-01-2020,CUST010794,Anjali Patel,P00033,Puzzle 1000pc,Home & Kitchen,UrbanStyle,5,598.29,0.00,538.46,5.07,3534.98,Amazon Pay,Shipped,San Diego,CA,India,SELL00471
81886,ORD0081887,26-09-2020,CUST031626,Vivaan Joshi,P00048,Wireless Charger,Toys & Games,HomeEase,5,596.47,0.00,536.82,2.68,3521.85,UPI,Shipped,Denver,CO,United States,SELL00354
4196,ORD0004197,22-02-2021,CUST022868,Kabir Gupta,P00029,T-Shirt,Home & Kitchen,Zenith,5,595.26,0.00,535.73,2.21,3514.24,Credit Card,Delivered,San Francisco,CA,United States,SELL00601
1929,ORD0001930,18-08-2023,CUST031209,Pooja Patel,P00025,Running Shoes,Books,KiddoFun,5,594.85,0.00,535.36,4.04,3513.65,UPI,Delivered,Phoenix,AZ,United Kingdom,SELL00955
58204,ORD0058205,19-10-2021,CUST033287,Priya Gupta,P00031,Kids Toy Car,Home & Kitchen,FitLife,5,594.46,0.00,535.01,5.74,3513.05,UPI,Delivered,San Antonio,TX,United States,SELL01072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38172,ORD0038173,18-06-2022,CUST025567,Pooja Kumar,P00040,Microphone,Toys & Games,ReadMore,1,5.89,0.00,0.47,0.05,6.41,Amazon Pay,Delivered,Charlotte,NC,United States,SELL01488
99805,ORD0099806,29-03-2024,CUST017538,Sneha Gupta,P00029,T-Shirt,Books,KiddoFun,1,6.08,0.05,0.29,0.12,6.19,UPI,Shipped,Denver,CO,United States,SELL01098
4730,ORD0004731,10-07-2023,CUST043142,Karan Mehta,P00007,Mechanical Keyboard,Books,NexPro,1,6.25,0.20,0.00,1.19,6.19,Debit Card,Delivered,San Jose,CA,India,SELL01655
68176,ORD0068177,29-03-2020,CUST004688,Mohit Kapoor,P00039,Graphic Tablet,Clothing,Zenith,1,5.26,0.20,0.76,0.62,5.59,Amazon Pay,Delivered,Austin,TX,United States,SELL00513
86771,ORD0086772,03-02-2022,CUST043262,Aarav Singh,P00029,T-Shirt,Sports & Outdoors,FitLife,1,5.57,0.30,0.31,0.06,4.27,Net Banking,Delivered,Jacksonville,FL,United States,SELL01896

In [50]:
df.query('TotalAmount >2000')

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
5,ORD0000006,31-12-2022,CUST042705,Karan Sharma,P00023,Cookware Set,Books,ReadMore,4,449.73,0.00,215.87,2.74,2017.53,UPI,Delivered,Los Angeles,CA,United States,SELL01494
17,ORD0000018,21-05-2022,CUST038237,Anjali Verma,P00039,Graphic Tablet,Toys & Games,KiddoFun,5,547.58,0.00,0.00,10.06,2747.96,Amazon Pay,Delivered,Seattle,WA,United States,SELL00132
18,ORD0000019,14-08-2024,CUST040211,Aditya Mehta,P00033,Puzzle 1000pc,Electronics,ReadMore,5,529.19,0.00,317.51,4.57,2968.03,Amazon Pay,Returned,Phoenix,AZ,United States,SELL01907
21,ORD0000022,25-08-2023,CUST048817,Pooja Sharma,P00010,Smartwatch,Books,ReadMore,4,493.47,0.00,98.69,11.80,2084.37,Credit Card,Delivered,Chicago,IL,Australia,SELL01672
22,ORD0000023,08-02-2022,CUST048828,Simran Reddy,P00003,Smartphone Case,Toys & Games,Apex,5,452.12,0.00,113.03,9.62,2383.25,Debit Card,Delivered,Phoenix,AZ,Canada,SELL01102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,ORD0099971,11-01-2024,CUST034218,Kabir Sharma,P00014,Drone Mini,Toys & Games,BrightLux,5,581.21,0.20,418.47,5.63,2748.94,Credit Card,Delivered,Houston,TX,United States,SELL00764
99974,ORD0099975,25-04-2024,CUST040916,Sahil Kapoor,P00023,Cookware Set,Toys & Games,Zenith,5,473.91,0.00,118.48,0.14,2488.17,Debit Card,Shipped,San Diego,CA,United States,SELL01492
99983,ORD0099984,14-02-2024,CUST033303,Arjun Mehta,P00027,Winter Jacket,Electronics,NexPro,4,480.40,0.00,153.73,6.21,2081.54,Amazon Pay,Delivered,San Diego,CA,United States,SELL00571
99986,ORD0099987,21-07-2021,CUST033288,Aarav Patel,P00007,Mechanical Keyboard,Clothing,ReadMore,4,528.88,0.05,100.49,3.77,2114.00,Credit Card,Returned,Seattle,WA,United States,SELL00691
99996,ORD0099997,24-11-2021,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449

In [51]:
df['ProductName'].value_counts()

ProductName
LED Desk Lamp                  2098
Water Bottle                   2088
Cookware Set                   2058
Electric Kettle                2054
Router                         2054
Yoga Mat                       2041
Memory Card 128GB              2039
Board Game                     2039
Smart Light Bulb               2036
Wireless Charger               2034
Mechanical Keyboard            2034
Microphone                     2034
Noise Cancelling Headphones    2031
Portable SSD 1TB               2030
Desk Organizer                 2026
Drone Mini                     2026
Action Camera                  2024
Office Chair                   2018
Vacuum Cleaner                 2017
Instant Pot                    2016
Webcam Full HD                 2013
Gaming Mouse                   2010
Wireless Earbuds               2008
Air Fryer                      2007
Dress Shirt                    2007
4K Monitor                     2006
Kids Toy Car                   2004
Running Shoes                  2002
HDMI Cable 2m                  2002
Phone Tripod                   1996
Laptop Sleeve                  1996
Smartwatch                     1989
Smartphone Case                1989
Graphic Tablet                 1981
T-Shirt                        1978
Projector Mini                 1976
External HDD 2TB               1975
Jeans                          1969
Power Bank 20000mAh            1966
Puzzle 1000pc                  1965
Novel Bestseller               1962
USB-C Charger                  1958
Winter Jacket                  1954
Sunglasses                     1952
Fitness Band                   1943
Desk Plant                     1941
Car Charger                    1917
Children's Book                1914
Bluetooth Speaker              1913
Backpack                       1910
Name: count, dtype: int64

In [52]:
df['Sales']= df['Quantity'] * df['UnitPrice']

In [53]:
df

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Sales
0,ORD0000001,31-01-2023,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967,319.77
1,ORD0000002,30-12-2023,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,251.37
2,ORD0000003,10-05-2022,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,...,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908,105.09
3,ORD0000004,18-07-2023,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,...,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,167.90
4,ORD0000005,04-02-2023,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,1031.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD0099996,07-03-2023,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,...,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041,984.68
99996,ORD0099997,24-11-2021,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,...,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449,2246.50
99997,ORD0099998,29-04-2023,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,...,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028,929.60
99998,ORD0099999,01-11-2021,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,...,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324,294.05
99999,ORD0100000,04-12-2021,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,...,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761,833.50

In [54]:
df['Sales'].sum()

np.float64(91021212.99000001)

In [55]:
pd.pivot_table(df, values='TotalAmount' , index= 'Category' , aggfunc=['sum','mean'])

                           sum        mean
                   TotalAmount TotalAmount
Category
Books              15261837.01  911.045667
Clothing           15253397.50  927.878673
Electronics        15584217.18  924.714720
Home & Kitchen     15163939.36  912.940359
Sports & Outdoors  15345571.88  913.209467
Toys & Games       15216684.99  919.881815

In [56]:
df.groupby('ProductName')['TotalAmount'].sum()

ProductName
4K Monitor                     1866774.35
Action Camera                  1829029.24
Air Fryer                      1789927.34
Backpack                       1749971.14
Bluetooth Speaker              1803356.76
Board Game                     1863310.96
Car Charger                    1779795.27
Children's Book                1738112.57
Cookware Set                   1877038.73
Desk Organizer                 1843103.26
Desk Plant                     1759672.62
Dress Shirt                    1896765.36
Drone Mini                     1816203.39
Electric Kettle                1905751.79
External HDD 2TB               1786108.33
Fitness Band                   1784149.50
Gaming Mouse                   1895103.98
Graphic Tablet                 1786772.26
HDMI Cable 2m                  1847856.25
Instant Pot                    1838639.12
Jeans                          1882591.82
Kids Toy Car                   1891082.43
LED Desk Lamp                  1921948.41
Laptop Sleeve                  1848297.80
Mechanical Keyboard            1906963.54
Memory Card 128GB              1935138.40
Microphone                     1871740.68
Noise Cancelling Headphones    1881108.57
Novel Bestseller               1803054.57
Office Chair                   1827426.35
Phone Tripod                   1866256.31
Portable SSD 1TB               1819377.38
Power Bank 20000mAh            1794738.58
Projector Mini                 1805867.58
Puzzle 1000pc                  1797812.49
Router                         1850756.20
Running Shoes                  1828658.19
Smart Light Bulb               1868940.58
Smartphone Case                1875421.41
Smartwatch                     1901275.59
Sunglasses                     1788111.81
T-Shirt                        1787855.05
USB-C Charger                  1763075.26
Vacuum Cleaner                 1855117.83
Water Bottle                   1895467.95
Webcam Full HD                 1799332.82
Winter Jacket                  1806053.51
Wireless Charger               1812628.92
Wireless Earbuds               1834207.58
Yoga Mat                       1847898.09
Name: TotalAmount, dtype: float64

In [57]:
df.groupby('Country')['TotalAmount'].sum()

Country
Australia          3789106.44
Canada             5323757.00
India             13875839.12
United Kingdom     4526896.86
United States     64310048.50
Name: TotalAmount, dtype: float64

In [58]:
df.loc[df['Sales']>1000]

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Sales
4,ORD0000005,04-02-2023,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,1031.28
5,ORD0000006,31-12-2022,CUST042705,Karan Sharma,P00023,Cookware Set,Books,ReadMore,4,449.73,...,215.87,2.74,2017.53,UPI,Delivered,Los Angeles,CA,United States,SELL01494,1798.92
11,ORD0000012,23-05-2023,CUST046088,Karan Kumar,P00042,Projector Mini,Home & Kitchen,KiddoFun,5,346.56,...,131.69,13.38,1791.23,Credit Card,Shipped,Charlotte,NC,Australia,SELL01160,1732.80
12,ORD0000013,26-11-2020,CUST026576,Simran Kapoor,P00018,Vacuum Cleaner,Home & Kitchen,Zenith,4,496.76,...,94.38,4.43,1986.50,UPI,Delivered,New York,NY,United States,SELL00719,1987.04
13,ORD0000014,22-01-2024,CUST006051,Pooja Sharma,P00040,Microphone,Home & Kitchen,Apex,3,523.27,...,188.38,8.04,1766.23,Debit Card,Shipped,Seattle,WA,United States,SELL00672,1569.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99986,ORD0099987,21-07-2021,CUST033288,Aarav Patel,P00007,Mechanical Keyboard,Clothing,ReadMore,4,528.88,...,100.49,3.77,2114.00,Credit Card,Returned,Seattle,WA,United States,SELL00691,2115.52
99989,ORD0099990,12-05-2021,CUST005788,Aarav Reddy,P00016,Air Fryer,Sports & Outdoors,UrbanStyle,5,341.55,...,68.31,14.15,1448.66,Net Banking,Delivered,San Diego,CA,United States,SELL01933,1707.75
99993,ORD0099994,04-05-2023,CUST045239,Mohit Sharma,P00029,T-Shirt,Toys & Games,CoreTech,3,592.56,...,113.77,3.82,1539.73,Credit Card,Cancelled,Denver,CO,United States,SELL00855,1777.68
99994,ORD0099995,09-01-2022,CUST028035,Kabir Kapoor,P00011,Fitness Band,Sports & Outdoors,ReadMore,5,240.94,...,54.21,14.66,1153.10,Amazon Pay,Delivered,Seattle,WA,India,SELL01073,1204.70
99996,ORD0099997,24-11-2021,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,...,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449,2246.50

In [59]:
#  Chaining Method

data=(
    df
    .query("Sales > 1000 and Country=='India'")
    .sort_values('Sales' , ascending=False)
)
data

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Sales
58985,ORD0058986,12-05-2022,CUST031096,Aman Singh,P00028,Jeans,Books,BrightLux,5,599.80,...,0.00,3.55,2852.60,Net Banking,Pending,Chicago,IL,India,SELL00221,2999.00
24565,ORD0024566,11-09-2020,CUST023461,Vivaan Gupta,P00014,Drone Mini,Clothing,Apex,5,599.51,...,227.81,0.93,3076.41,Debit Card,Delivered,Austin,TX,India,SELL01136,2997.55
71304,ORD0071305,23-10-2022,CUST025737,Karan Patel,P00043,HDMI Cable 2m,Books,KiddoFun,5,599.50,...,149.88,14.22,3161.60,Cash on Delivery,Delivered,Seattle,WA,India,SELL01241,2997.50
33003,ORD0033004,30-10-2022,CUST039524,Sneha Kapoor,P00037,Router,Sports & Outdoors,Apex,5,599.39,...,359.63,10.74,3367.32,Debit Card,Delivered,San Jose,CA,India,SELL00140,2996.95
42951,ORD0042952,19-01-2020,CUST006522,Sahil Gupta,P00038,External HDD 2TB,Clothing,Apex,5,599.29,...,0.00,8.88,2705.68,Debit Card,Delivered,San Jose,CA,India,SELL01791,2996.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2641,ORD0002642,22-05-2020,CUST046780,Simran Patel,P00004,USB-C Charger,Toys & Games,HomeEase,2,500.26,...,80.04,14.08,1094.64,UPI,Delivered,Austin,TX,India,SELL00225,1000.52
67945,ORD0067946,11-04-2024,CUST031000,Aditya Reddy,P00016,Air Fryer,Toys & Games,FitLife,3,333.49,...,108.05,4.24,1012.71,Debit Card,Delivered,Dallas,TX,India,SELL01747,1000.47
56193,ORD0056194,04-09-2023,CUST012954,Sahil Gupta,P00049,Children's Book,Clothing,KiddoFun,2,500.19,...,80.03,8.38,1088.79,UPI,Delivered,Washington,DC,India,SELL00408,1000.38
20067,ORD0020068,18-09-2021,CUST038392,Aman Joshi,P00027,Winter Jacket,Electronics,UrbanStyle,2,500.05,...,0.00,14.83,1014.93,Credit Card,Shipped,Austin,TX,India,SELL00027,1000.10
3879,ORD0003880,29-08-2023,CUST003123,Vihaan Kapoor,P00032,Board Game,Books,Apex,3,333.34,...,50.00,9.48,1059.50,Net Banking,Shipped,Denver,CO,India,SELL01876,1000.02

In [60]:
df['OrderID'].count()

np.int64(100000)

In [61]:
df['Previous_sales']=df['Sales'].shift(1)

In [62]:
df

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Sales,Previous_sales
0,ORD0000001,31-01-2023,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967,319.77,NaN
1,ORD0000002,30-12-2023,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,251.37,319.77
2,ORD0000003,10-05-2022,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,...,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908,105.09,251.37
3,ORD0000004,18-07-2023,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,...,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,167.90,105.09
4,ORD0000005,04-02-2023,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,1031.28,167.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD0099996,07-03-2023,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,...,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041,984.68,1204.70
99996,ORD0099997,24-11-2021,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,...,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449,2246.50,984.68
99997,ORD0099998,29-04-2023,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,...,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028,929.60,2246.50
99998,ORD0099999,01-11-2021,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,...,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324,294.05,929.60
99999,ORD0100000,04-12-2021,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,...,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761,833.50,294.05

In [68]:
from sqlalchemy import create_engine

username='root'
password='mysql12'
host='localhost'
port='3306'
database='project'

engine=create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

table_name='amazon'

df.to_sql(table_name , engine , if_exists='replace',index=False)

print(" Amazon Data Successfully Loaded into the mysql")

 Amazon Data Successfully Loaded into the mysql

In [69]:
df.shape

(100000, 22)